{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "Minicraft",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "3mkkrj6lznannbz3jiqs4ywx6i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Minicraft-1.0.0.jar",
          "url": "Minicraft-1.0.0.jar",
          "size": 264281,
          "sha512": "44b1269aea57f7731de00da574a1fd1e6202c7e4d11846fbd745a99c3f4d7019aa9e6506e5d67fa1f4107228af6141d4ccbcd7a8ab5d8f4540c1dec25d5034be",
          "sha256": "1330c958a7fc76771f1ddb770ab9f0c9ff636661f2fcc1fbc1c21fad7249af64",
          "sha1": "d55f9a90478f773baef412d23db0657256ae176f",
          "md5": "6c0402941f23ef129bddd985425f1377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Minicraft-1.0.0.jar",
          "url": "Minicraft-1.0.0.jar",
          "size": 264281,
          "sha512": "44b1269aea57f7731de00da574a1fd1e6202c7e4d11846fbd745a99c3f4d7019aa9e6506e5d67fa1f4107228af6141d4ccbcd7a8ab5d8f4540c1dec25d5034be",
          "sha256": "1330c958a7fc76771f1ddb770ab9f0c9ff636661f2fcc1fbc1c21fad7249af64",
          "sha1": "d55f9a90478f773baef412d23db0657256ae176f",
          "md5": "6c0402941f23ef129bddd985425f1377"
        }
      ]
    }
  ]
}
